#ifndef IMAGE_TYPE_H
#define IMAGE_TYPE_H

enum image_t {BASE, DSF, STD_DEV, SPATIAL_PROFILE, SPECTRAL_PROFILE, SPATIAL_MEAN, SPECTRAL_MEAN};

enum camera_t {DEFAULT, ITB, CL_6604A, CL_6604B};

enum source_t {SSD, DEBUG, CAMERA_LINK};

#endif // IMAGE_TYPE_H
